apiVersion: v1
kind: Service
metadata:
  name: slave1
  labels:
    app: slave
    service: slave1
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: slave
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-slave
  labels:
    account: slave
