apiVersion: v1
kind: Service
metadata:
  name: slave2
  labels:
    app: slave2
    service: slave2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: slave2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-slave2
  labels:
    account: slave2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave2
  labels:
    app: slave2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave2
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: slave2
        version: v1
    spec:
      containers:
      - name: slave2
        image: docker.io/mizmorr/server:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
