apiVersion: batch/v1
kind: Job
metadata:
  name: client-job
spec:
  template:
    spec:
      containers:
      - name: client
        image: byrnedo/alpine-curl
        command: ["/bin/sh", "-c",  "curl -s http://${SERVER2_SERVICE_HOST}:${SERVER2_SERVICE_PORT}"]
      restartPolicy: Never
  backoffLimit: 4
