apiVersion: v1
kind: ReplicationController
metadata:
  name: listener
spec:
  replicas:  3
  selector:
    app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: mizmorr/listener
        ports:
        -  containerPort: 8080
