apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listener-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: listener-ingress.mizmorr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: http-server
                port:
                  number: 8080

