apiVersion: v1
kind: Service
metadata:
  name: cluster-zero
  labels:
    app: cluster-zero
    service: cluster-zero
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: cluster-zero
---
