apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cluster-second
        version: 6-core
    name: 6-core
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cluster-second
            version: 6-core
    template:
        metadata:
            labels:
                app: cluster-second
                version: 6-core
        spec:
            containers:
                - image: docker.io/mizmorr/server:v5
                  imagePullPolicy: Always
                  name: server
                  ports:
                    - containerPort: 9080
