apiVersion: v1
kind: Service
metadata:
  name: cluster-second
  labels:
    app: cluster-second
    service: cluster-second
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: cluster-second
---
