apiVersion: v1
kind: Service
metadata:
  name: referencer
  labels:
    app: referencer
    service: referencer
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: referencer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-referencer
  labels:
    account: referencer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: referencer-deployment
  labels:
    app: referencer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: referencer
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: referencer
        version: v1
    spec:
      containers:
      - name: server
        image: docker.io/mizmorr/server:referencer
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
