apiVersion: v1
kind: Service
metadata:
  name: cluster-first
  labels:
    app: cluster-first
    service: cluster-first
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: cluster-first
---
